/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import java.awt.Color;

/**
 *
 * @author stefa
 */
public class loginult extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginult.class.getName());
    int xMouse,yMouse;
  
    public loginult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        usertitle = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        userSeparator = new javax.swing.JSeparator();
        passwordtitle = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        passwordSeparator = new javax.swing.JSeparator();
        Logo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        xButton = new javax.swing.JLabel();
        enter = new javax.swing.JPanel();
        enterText = new javax.swing.JLabel();
        imagendefondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Roboto", 1, 26)); // NOI18N
        title.setText("Iniciar Sesión");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 210, 40));

        usertitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        usertitle.setText("USUARIO");
        jPanel1.add(usertitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        userfield.setBackground(new java.awt.Color(246, 246, 246));
        userfield.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        userfield.setText("Ingrese su nombre de usuario");
        userfield.setBorder(null);
        userfield.setSelectionColor(new java.awt.Color(51, 51, 255));
        userfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userfieldMousePressed(evt);
            }
        });
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });
        jPanel1.add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 300, 20));

        userSeparator.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(userSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 300, 10));

        passwordtitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        passwordtitle.setForeground(new java.awt.Color(204, 204, 204));
        passwordtitle.setText("CONTRASEÑA");
        jPanel1.add(passwordtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        passwordfield.setBackground(new java.awt.Color(246, 246, 246));
        passwordfield.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        passwordfield.setText("********");
        passwordfield.setBorder(null);
        passwordfield.setSelectionColor(new java.awt.Color(51, 51, 255));
        passwordfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordfieldMousePressed(evt);
            }
        });
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 300, 20));

        passwordSeparator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(passwordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, 10));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/interfaz/logoULT.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        xButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        xButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xButton.setText("X");
        xButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(xButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 772, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 20));

        enterText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        enterText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterText.setText("Entrar");
        enterText.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        enterText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enterText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout enterLayout = new javax.swing.GroupLayout(enter);
        enter.setLayout(enterLayout);
        enterLayout.setHorizontalGroup(
            enterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enterText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        enterLayout.setVerticalGroup(
            enterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enterText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 120, 40));

        imagendefondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/interfaz/barcofondoULT.png"))); // NOI18N
        jPanel1.add(imagendefondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void enterTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterTextMouseEntered
       enter.setBackground(new Color(195,195,195));
    }//GEN-LAST:event_enterTextMouseEntered

    @SuppressWarnings("unused")
    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
 
    }//GEN-LAST:event_exitBtnMouseEntered
    @SuppressWarnings("unused")
    private void XcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XcloseMouseEntered
    
    }//GEN-LAST:event_XcloseMouseEntered

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void xButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xButtonMouseEntered
        exitBtn.setBackground(Color.gray);
    }//GEN-LAST:event_xButtonMouseEntered

    private void xButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xButtonMouseClicked

    private void xButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xButtonMouseExited
        exitBtn.setBackground(new Color(214,217,223));
    }//GEN-LAST:event_xButtonMouseExited

    private void enterTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterTextMouseExited
       enter.setBackground(new Color(214,217,223));
    }//GEN-LAST:event_enterTextMouseExited

    private void userfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userfieldMousePressed
        if (userfield.getText().equals("Ingrese su nombre de usuario")) {
            userfield.setText("");
        }
        if (String.valueOf(passwordfield.getPassword()).isEmpty()) {
            passwordfield.setText("********");
        }
    }//GEN-LAST:event_userfieldMousePressed

    private void passwordfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordfieldMousePressed
        if (String.valueOf(passwordfield.getPassword()).equals("********")) {
            passwordfield.setText("");
        }
        if (userfield.getText().isEmpty()) {
            userfield.setText("Ingrese su nombre de usuario");
        }        
    }//GEN-LAST:event_passwordfieldMousePressed

    private void enterTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterTextMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + userfield.getText() + "\nContraseña: " + String.valueOf(passwordfield.getPassword()), "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_enterTextMouseClicked

    
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Configura el look and feel Nimbus (opcional) */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, "Error al configurar Nimbus LookAndFeel", ex);
        // Fallback al look and feel por defecto
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al configurar el look and feel por defecto", e);
        }
    }

    /* Crea y muestra la ventana principal */
    java.awt.EventQueue.invokeLater(() -> {
        loginult ventanaLogin = new loginult();
        
        // Configuración básica para asegurar visibilidad
        ventanaLogin.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE); // Cierra la app al salir
        ventanaLogin.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        ventanaLogin.pack(); // Ajusta el tamaño automáticamente
        ventanaLogin.setVisible(true); // Hace visible la ventana
        
        // Opcional: Personaliza título y tamaño
        ventanaLogin.setTitle("Inicio de Sesión"); // Ancho x Alto (píxeles)
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel enter;
    private javax.swing.JLabel enterText;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imagendefondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel passwordtitle;
    private javax.swing.JLabel title;
    private javax.swing.JSeparator userSeparator;
    private javax.swing.JTextField userfield;
    private javax.swing.JLabel usertitle;
    private javax.swing.JLabel xButton;
    // End of variables declaration//GEN-END:variables
}
