/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

/**
 *
 * @author carmelomoschella
 */
public class login extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        passwordinput = new javax.swing.JLabel();
        passwordtitle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        usertitle = new javax.swing.JLabel();
        userinput = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        imagendefondo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Pasted Graphic.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        passwordinput.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        passwordinput.setForeground(new java.awt.Color(204, 204, 204));
        passwordinput.setText("Ingrese su contraseña");
        jPanel1.add(passwordinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        passwordtitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        passwordtitle.setText("CONTRASEÑA");
        jPanel1.add(passwordtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        title.setFont(new java.awt.Font("Roboto", 1, 26)); // NOI18N
        title.setText("Iniciar Sesión");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 40));

        usertitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        usertitle.setText("USUARIO");
        jPanel1.add(usertitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        userinput.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        userinput.setForeground(new java.awt.Color(204, 204, 204));
        userinput.setText("Ingrese su nombre de usuario");
        jPanel1.add(userinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 300, 10));

        imagendefondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Gabarra de fondo.jpeg"))); // NOI18N
        jPanel1.add(imagendefondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 300, 10));

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 310, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagendefondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passwordinput;
    private javax.swing.JLabel passwordtitle;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userinput;
    private javax.swing.JLabel usertitle;
    // End of variables declaration//GEN-END:variables
}
